// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANE4sfttXjksxAh-4PeYZBGp4B6hVZbZY',
    appId: '1:867038185833:web:874e75c32c1d7b61d815f8',
    messagingSenderId: '867038185833',
    projectId: 'buumer-f8cb7',
    authDomain: 'buumer-f8cb7.firebaseapp.com',
    storageBucket: 'buumer-f8cb7.firebasestorage.app',
    measurementId: 'G-6REGCZ0GFL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG-_MwVEx8DYi4qTjxUUlqSPOFXRVGE_4',
    appId: '1:867038185833:android:e43ca65f98283949d815f8',
    messagingSenderId: '867038185833',
    projectId: 'buumer-f8cb7',
    storageBucket: 'buumer-f8cb7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj2z8TL0e01VlOdYdiQVvfedkdX8rZkGU',
    appId: '1:867038185833:ios:aff3cb6132b195dad815f8',
    messagingSenderId: '867038185833',
    projectId: 'buumer-f8cb7',
    storageBucket: 'buumer-f8cb7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj2z8TL0e01VlOdYdiQVvfedkdX8rZkGU',
    appId: '1:867038185833:ios:aff3cb6132b195dad815f8',
    messagingSenderId: '867038185833',
    projectId: 'buumer-f8cb7',
    storageBucket: 'buumer-f8cb7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANE4sfttXjksxAh-4PeYZBGp4B6hVZbZY',
    appId: '1:867038185833:web:c4fc98a26aff0bb5d815f8',
    messagingSenderId: '867038185833',
    projectId: 'buumer-f8cb7',
    authDomain: 'buumer-f8cb7.firebaseapp.com',
    storageBucket: 'buumer-f8cb7.firebasestorage.app',
    measurementId: 'G-P84GQDFY8E',
  );
}
